version = "0.9.0"
deployment = "deployment.toml"

[rust]
workspace_dir = "."
toolchain = "nightly-2022-08-01"
docker_image = "thewawar/ckb-capsule:2022-08-01"

[[contracts]]
name = "ckb-lua-scripts"
template_type = "Rust"
