
[package]
name = "ckb-lib-lua"
version = "0.1.0"
authors = ["dylan <duanyytop@gmail.com>"]
edition = "2021"

[dependencies]
ckb-std = {package = "ckb-std", git = "https://github.com/duanyytop/ckb-std", branch="master"}

[build-dependencies]
blake2b-rs = "0.2.0"